### ISSUE TITLE
Use ember-auto-import for packaging?

### ISSUE THREAD

**Issue by bgentry** [bgentry/ember-apollo-client#145]
Should we be using [ember-auto-import](https://github.com/ef4/ember-auto-import) for packaging dependencies? Any advantages/disadvantages compared to our current setup?

The obvious advantage is that it's a shared community solution and we'd no longer need to maintain our own packaging setup. Also it should make for a clean transition to future ember versions where that functionality is available out-of-the-box.

Thoughts? Especially @dfreeman 😄

**Comment by dfreeman** [comment]
I haven't had the chance to play with it in one of my own projects yet, but using ember-auto-import seems like a no-brainer if it has a good story for addons. 👍

**Comment by bgentry** [comment]
My main concern about this upgrade is about whether we could maintain compatibility with [the existing package configuration API](https://github.com/bgentry/ember-apollo-client#configuration) or if we'd need to do a major version bump.

Other than that this should be a straightforward switch to make.

**Comment by jasonmit** [comment]
> My main concern about this upgrade is about whether we could maintain compatibility with the existing package configuration API or if we'd need to do a major version bump.

I feel `exclude` and `include` should be removed.  My rational is it wasn't immediately clear that many of the libs could not safely be removed (i.e., `apollo-cache-inmemory`).  I discovered that after the service module was accessed and throwing errors because of 
https://github.com/bgentry/ember-apollo-client/blob/master/addon/services/apollo.js#L1-L20

If a user needs to import these additional libs they should be dependent on importing them via ember-auto-import explicitly within their app.

**Comment by jasonmit** [comment]
https://github.com/ef4/ember-auto-import/issues/74 will need to be resolved before I can go further.  Will fix ember-auto-import once I get some clarity if this issue was done intentionally or not.
