### ISSUE TITLE
Improved unsubscribe design

### ISSUE THREAD

**Issue by bgentry** [bgentry/ember-apollo-client#19]
I was discussing this issue with @viniciussbs on Slack the other day. Opening an issue to solicit ideas.

With Apollo Client, after performing a `watchQuery`, you get back an [“observable” object](http://dev.apollodata.com/core/apollo-client-api.html#ObservableQuery). The ember-apollo-client Apollo service then "subscribes" to this observable, and the resulting subscription later needs to be `unsubscribe`d from when you no longer want it to get updated w/ new data from the store. Typically this is done when you exit a route, or when the component is being destroyed. My initial version of this addon used an ugly hack to enable this, by exposing an `_apolloUnsubscribe` function on the returned data and making the user responsible for calling it.

@viniciussbs and I are both unhappy with the current way that ember-apollo-client puts the onus on the user to unsubscribe from watched data whenever they're done w/ it. I’m trying to come up with a more user-friendly design that still meshes well w/ Ember.

One idea I had is that instead of injecting the `apollo` service directly into routes/components, you’d use some sort of mixin that would function as a proxy. It would still be available via `this.get('apollo')`, and would proxy all calls to the actual apollo service, except that it would also track queries and route/component lifecycles. Then it could automatically unsubscribe from anything that was queried within the route/component when teardown is happening.

This might also enable some better designs for pagination (see #18). If the tracked observables are easily available to the developer (say with `this.get('apolloQueries.myActiveQueryName')`), then it would be trivial to call `fetchMore()` on the observable when you want to get another page of results.

One of the key design goals I'd like to achieve with this project is to avoid layering too much on top of Apollo Client. I hope that means it's easier to keep up with the project and we can avoid situations where functionality is available in the upstream but not easy to use in this addon.

Thoughts on whether this is a good idea or on how to implement it? Are there other projects out there with a similar model, where a service is wrapped to make it route-aware or component-aware?

**Comment by viniciussbs** [comment]
I have a use case for this.

Let's say a route could have actions to open modals with a query per modal. That leads to many query subscriptions into the same route asking to be unsubscribed when you exit the route.

I have a similar use case into my application, but all actions that open modals are into the route `Application` - because the modals can be opened from any route. In this case, the route's query manager won't help. Calling something like `this.queryManagerFor('application')` inside the route could help. This is a corner case, though. I can solve this doing the query inside the modals components - I was avoiding it to follow the DDAU style.

**Comment by bgentry** [comment]
Fixed by #20.
