### ISSUE TITLE
Import multiple mutation as alias

### ISSUE THREAD

**Issue by m0rgul** [bgentry/ember-apollo-client#32]
@bgentry

`import { default as submitAnswers } from '../../gql/mutations/submitAnswers';`
`import { default as submit } from '../../gql/mutations/submit';`

`this.get('apollo').mutate({ submitAnswers, variables }, 'submitAnswers')` throws an error -> **TypeError: Cannot read property 'kind' of undefined at checkDocument**

What is the proper way of using 2 mutations in the same controller?

**Comment by n1ru4l** [comment]
```javascript
import submitAnswers from '../../gql/mutations/submitAnswers';
import submit from '../../gql/mutations/submit';
```
This works for me

**Comment by m0rgul** [comment]
For me it's not working :(

Could it have anything to do with the Ember version?

`ember-cli: 2.10.0`
`node: 6.10.3`
`os: linux x64`
`bower_components/ember/.bower.json:  "version": "2.13.3"`

And the mutation files look like this:
[submitAnswers.graphql.txt](https://github.com/bgentry/ember-apollo-client/files/1077578/submitAnswers.graphql.txt)
[submit.graphql.txt](https://github.com/bgentry/ember-apollo-client/files/1077579/submit.graphql.txt)

*Added txt extension to be able to post them here

**Comment by n1ru4l** [comment]
@m0rgul You can post the queries with a codeblock https://help.github.com/articles/creating-and-highlighting-code-blocks/ (github supports graphql highlighting)

You should prefer absolute imports e.g. `<project-name>/gql/mutations/submit`

**Comment by m0rgul** [comment]
I did a `console.log` on both imports, both are objects, they look the same (at first sight).

If I just do `import mutation from '...'`, it works, however if I import it with an alias, it fails with the error. 

And a small correction, I import them in a route (tho I don't think that should make any difference)

**Comment by n1ru4l** [comment]
Copied from my current project:
```javascript
import wrapperDetailQuery from 'project-frontend/gql/queries/wrapper-detail';
import updateWrapperMutation from 'project-frontend/gql/mutations/update-wrapper';
import updateQuestionMutation from 'project-frontend/gql/mutations/update-question';
import deleteQuestionMutation from 'project-frontend/gql/mutations/delete-question';
import createQuestionMutation from 'project-frontend/gql/mutations/create-question';
```

```
user@MacBook-Pro:~/Projects/work/project-frontend$ npm ls | grep "apollo"
├─┬ ember-apollo-client@0.3.2
│ ├─┬ apollo-client@1.4.2
```

Works for me...

**Comment by m0rgul** [comment]
Sorted it out by doing this:

`this.get('apollo').mutate({ mutation: submitAnswers, variables }, 'submitAnswers')`

**Comment by bgentry** [comment]
Sounds resolved.

**Comment by notmessenger** [comment]
Running `ember@2.14.1` and `ember-apollo-client@0.3.2` I also ran into a problem when wanting an alias, such as:

`import organizationsQuery from 'my-project/gql/queries/organizations'`

I would receive the error of `Error: query option is required. You must specify your GraphQL document in the query option.`

Converting my call from

`this.get('apollo').queryOnce({organizationsQuery})`

to

`this.get('apollo').queryOnce({query: organizationsQuery})`

resolved the issue though, just as it did for @m0rgul

This makes sense though since when it was imported as `query` instead of `organizationsQuery` the ES6 syntax of `.queryOnce({query})` was being interpreted as `.queryOnce({query: query})` whereas `.queryOnce({organizationsQuery})` is interpreted as `.queryOnce({organizationsQuery: organizationsQuery})` which is an incorrect property to pass to `queryOnce()`
