### ISSUE TITLE
Auth support

### ISSUE THREAD

**Issue by bgentry** [bgentry/ember-apollo-client#5]
There's no official mechanism for providing authorization headers or manipulating API requests before they go out. It should be pretty easy to do even without official support in this addon due to the way the `client` is exposed on the `apollo` service, and Apollo Client's built-in middleware support.

Even if no new code needs to be added to support this, it should be documented and tested explicitly.

**Comment by dfreeman** [comment]
Today many apps use `ember-ajax` as a single point of configuration for this kind of thing so that both ad-hoc and Ember Data requests (via the [adapter mixin](https://github.com/ember-cli/ember-ajax#usage-with-ember-data)) get the same treatment. That setup fits pretty nicely with the layered approach to networking Tom Dale [gisted](https://gist.github.com/tomdale/203ea125acd0be8b5f1f) a while back.

Using Apollo Client's built-in middleware support is definitely a viable approach, but do you have any thoughts on whether there's a reasonable way to integrate with some of the conventional Ember networking utilities? It seems like a real usability win if `ember-apollo-client` could easily work with an existing auth setup.

**Comment by bgentry** [comment]
@dfreeman do you have a sense for the current state of the proposals in Tom's gist? I love the idea of doing something like you described. What that would involve (I think) is a creating a [custom NetworkInterface](http://dev.apollodata.com/core/network.html#custom-network-interface) for ApolloClient. Presumably we could extend the `HTTPFetchNetworkInterface` [here](https://github.com/apollostack/apollo-client/blob/master/src/transport/networkInterface.ts). It might be possible to make it work with only an override of `fetchFromRemoteEndpoint`. If so, it might turn out to be an easy integration!

For expediency, I went ahead and implemented a middleware approach in my own app. Here's what that looks like for the naïve example of a static auth header:

```js
import ApolloService from 'ember-apollo-client/services/apollo';
import Ember from 'ember';

const { inject: { service } } = Ember;

export default ApolloService.extend({
  init() {
    this._super(...arguments);
    this.get('client').networkInterface.use([{
      applyMiddleware: (req, next) => this._runAuthorize(req, next)
    }]);
  },

  _runAuthorize(req, next) {
    if (!req.options.headers) {
      req.options.headers = {}; // Create the headers object if needed.
    }
    req.options.headers.authorization = 'Bearer foo-bar-token';
    next();
  }
});
```

In my actual app, I initiated an ember-simple-auth authorizer in `_runAuthorize` and used its response to set headers (rather than a static value). Looks like this:

```js
this.get('session').authorize('authorizer:oauth2', (headerName, headerContent) => {
  ... // set the auth header as shown above
});
```

I'm thinking that it would be useful to document this in the readme. For now, it's useful as an immediate solution to authorization. However, my assumption is that folks will likely still want to add [middleware](http://dev.apollodata.com/core/network.html#networkInterfaceMiddleware) or [afterware](http://dev.apollodata.com/core/network.html#networkInterfaceAfterware) even if we do end up integrating a network layer solution like ember-fetch and ember-ajax. A middleware example would remain useful in either case.

Do you have any suggestions to improve the middleware example? I'll get a PR open with a doc fix in the next couple of days.

**Comment by arkadiyk** [comment]
Personally I would prefer the `ember-ajax` way to configure the plugin. There is one big drawback though. You always need to extend  the `emebr-ajax` service in order to provide an endpoint URL.

Right now I use my local branch of this plugin where I defined a hook for the token method: https://github.com/arkadiyk/ember-apollo-client/commit/c9cd32031924fc3562143484462b4f43ca2000ce 

And I provide a callbacks in a service which extends the one from the plugin:

```js
import Ember from 'ember';
import Apollo from 'ember-apollo-client/services/apollo';
import config from '../config/environment';

const {
  computed: { alias },
  inject: { service },
} = Ember;

export default Apollo.extend({
  apiURL: config.apiURL,
  session: service(),
  token: alias('session.session.content.authenticated.jwt')
});
```

**Comment by viniciussbs** [comment]
@arkadiyk I was planning to implement something similar next week because I need a different `dataIdFromObject` implementation. So, +1 for this configuration style.

About the auth configuration, this implementation will only work with OAuth2. I think the service shouldn't implement an authentication logic. Instead of relay on a `token` property, I suggest a `middlewares` one:

```
const middlewares = get(this, 'middlewares');

if (middlewares) {
  let middlewares = middlewares.map(applyMiddleware => ({ applyMiddleware });
  networkInterface.use(middlewares);
}
```

In my case I would implement two middlewares: one for auth logic and another one for i18n - I need to set `Accepted-Language` header for all resquests. This is how I am doing it today:

```
init() {
  this._super(...arguments);
  get(this, 'client').networkInterface.use([
    { applyMiddleware: (req, next) => this._setLocale(req, next) },
    { applyMiddleware: (req, next) => this._runAuthorize(req, next) }
  ]);
}
```

**Comment by arkadiyk** [comment]
@viniciussbs agreed, your solution is more flexible. It requires the extension to be aware of how to create the Apollo middleware (`next()` method) but I don't think it is a bad thing. I would be interested what @bgentry take on what approach should be taking to make the plugin configurable?

**Comment by viniciussbs** [comment]
This middleware configuration is related to this issue about network interfaces: #6

**Comment by viniciussbs** [comment]
I would like to write something like this:

```
import ApolloService from 'ember-apollo-client/services/apollo';
import WebsocketNetworkInterface from 'my-app/mixins/apollo/websockt-network-interface';
import AuthMiddleware from 'my-app/mixins/apollo/auth-middleware';
import LocaleMiddleware from 'my-app/mixins/apollo/locale-middleware';

export default ApolloService.extend(WebsocketNetworkInterface, AuthMiddleware, LocaleMiddleware);
```
