### ISSUE TITLE
Need to inject `config:environment` into all unit tests that touch Apollo

### ISSUE THREAD

**Issue by bgentry** [bgentry/ember-apollo-client#55]
Follow-up from #53.

It's a bit annoying to have to use a `needs: ['config:environment']` in addition to already needing a `service:apollo` in any unit test that touches Apollo. As of now, this blows up on the `config.apollo` call when not using that injection because `config` is undefined [here](https://github.com/bgentry/ember-apollo-client/blob/178dbb7f836b26efcfcf735e0e71520e5630474d/addon/services/apollo.js#L60-L63).

One way I'm working around this in my own tests is with this hack:

```js
// used in environments without injected `config:environment` (i.e. unit tests):
const defaultOptions = {
  apiURL: "http://testserver.example/v1/graph",
};

export default ApolloService.extend({
  options: computed(function() {
    let config = getOwner(this).resolveRegistration("config:environment");
    if (config && config.apollo) {
      return config.apollo;
    } else if (testing) {
      return defaultOptions;
    }
    throw new Error("no Apollo service options defined");
  }),
  // ...
});
```

I'm not sure if there's a better way to handle this. At the very least, I think there should be a descriptive error like this when a required config isn't set up or available.

**Comment by dfreeman** [comment]
One alternative would be to instruct folks to use `integration: true` rather than `needs: [...]` in their apollo-related unit tests, but that may feel kind of weird until [it becomes the documented norm and `integration` goes away](https://github.com/emberjs/rfcs/pull/229).

Either way, falling back to default options in tests seems like an ergonomic win 👍
