### ISSUE TITLE
Configurable networkInterface

### ISSUE THREAD

**Issue by delkopiso** [bgentry/ember-apollo-client#6]
It would be really useful to make the networkInterface configurable. So a user could easily extend the ApolloService and specify a different type of transport (e,g, batching).

**Comment by bgentry** [comment]
Yes, I think that would be great! Do you have any thoughts on how this might work? Maybe you could propose an example of how you'd like your service to look when configuring the network interface?

FWIW I believe you can do this in a hacky way now:

```js
import ApolloService from 'ember-apollo-client/services/apollo';

export default ApolloService.extend({
  init() {
    this._super(...arguments);
    this.get('client').networkInterface = this.myNetworkInterface();
  },

  myNetworkInterface() {
    return ...
  }
});
```

**Comment by bgentry** [comment]
I would also be interested in how this might fit in with the ember-ajax idea proposed by @dfreeman (https://github.com/bgentry/ember-apollo-client/issues/5#issuecomment-271665188)

**Comment by viniciussbs** [comment]
I'll take a look at this in a near future because maybe I'll need a custom transport to send queries over Websockets.

**Comment by n1ru4l** [comment]
A simple way would be to to make the object which is passed to the ApolloClient constructor a property on the service. So any user that wanted to extend it could overwrite those defaults.

This would however not work with the following lines ( since apiUrl is only available in the constructor ):
```javascript
    let client = new ApolloClient({
      networkInterface: createNetworkInterface({ uri: apiURL }),
      // This dataIdFromObject only works with globally unique IDs. Might want
      // to make it configurable.
      dataIdFromObject: (o) => o.id
    });
```

A second thought would be to implement a settings method which can be overwritten when extending the service. I would make a pull request for this ( if you are okay with that option )

```javascript

export default Service.extend({
  client: null,

  settings( apiUrl ) {
    return {
      networkInterface: createNetworkInterface({ uri: apiURL }),
      // This dataIdFromObject only works with globally unique IDs. Might want
      // to make it configurable.
      dataIdFromObject: (o) => o.id
    }
  },
  init() {
    this._super(...arguments);

    const apiURL = this.get('options.apiURL');
    const owner = getOwner(this);
    owner.registerOptionsForType('apollo', { instantiate: false });
    
    const settings = this.settings( apiURL  );
    let client = new ApolloClient( settings  );
    this.set('client', client);

    if (testing) {
      this._registerWaiter();
    }
  },
  ...
}
```

I would not like and recommend the idea of having some kind of custom configuration which is transformed into a ApolloClient constructor ( to keep things simple ).

**Comment by n1ru4l** [comment]
@bgentry what is your opinion on this?

**Comment by viniciussbs** [comment]
@n1ru4l I've suggested something similar to @bgentry on issue #5.

```
{
  // ...

  middlewares: [],
  afterwares: [],
  dataIdFromObject: null,

  init() {
    this._super(...arguments);
    getOwner(this).registerOptionsForType('apollo', { instantiate: false });

    let clientOptions = this.getClientOptions();
    let client = new ApolloClient(clientOptions);

    set(this, 'client', client);

    if (testing) {
      this._registerWaiter();
    }
  },

  getClientOptions() {
    let dataIdFromObject = this.dataIdFromObject;
    let networkInterface = this.createNetworkInterface();

    return { networkInterface, dataIdFromObject };
  },

  createNetworkInterface() {
    let apiURL = get(this, 'options.apiURL');
    let middlewares = get(this, 'middlewares');
    let afterwares = get(this, 'afterwares');
    let networkInterface = createNetworkInterface({ uri: apiURL });

    networkInterface.use(middlewares);
    networkInterface.useAfter(afterwares);

    return networkInterface;
  },

  // ...
}
```

So, inside my app, I could extend default implantation to add my middlewares and afterwares:

```
export default Apollo.extend({
  middlewares: [
    { applyMiddleware: this.authorize.bind(this) },
    { applyMiddleware: this.setAcceptedLanguages.bind(this) }
  ],

  authorize(req, next) {
    // ...
  },

  setAcceptedLanguages(req, next) {
    // ...
  },
});
```

I've set `dataIdFromObject` to `null` because [default implementation](https://github.com/apollographql/apollo-client/blob/master/src/ApolloClient.ts#L102-L112) handles unique object IDs.

**Comment by bgentry** [comment]
Hey there, sorry I've dropped the ball on weighing in here. Been trying to get my product off the ground.

I totally agree that it should be trivial to override any aspect of the Apollo service. What's there now is essentially what I needed to make it work for myself and I don't expect it to suit everybody's needs. I'd definitely welcome any contributions that move us in that direction.

My general preference is to make explicit APIs for any aspect that might need to be overridden (network interfaces, client options, etc.) so that overriding `init()` should almost never be necessary. It looks like @viniciussbs' proposals are on the right track there and I'd love to see them PR'd!

I wish I could take a more active role in driving this forward myself but I'm just not able to right now. I can at least promise to give prompt review and feedback on any PRs that you folks come up with.

**Comment by viniciussbs** [comment]
@bgentry I'll wait PR #16 to be merged before working on this PR.

**Comment by bgentry** [comment]
@viniciussbs ok. I'm actually going to try to handle part of this because I need to set up a `fragmentMatcher` for my client. I was thinking of starting out by altering the apollo service so the client is initialized like so:

```js
let client = new ApolloClient(this.get('clientOptions'));
```

Then `clientOptions` on the service would be set with some defaults which could easily be overridden. But thinking that wouldn't work unless it was a function call because you wouldn't have the `this` context of the service object. Thoughts on that?

**Comment by bgentry** [comment]
#16 is merged now anyway.

**Comment by bgentry** [comment]
This should be possible after #17. You should be able to configure any of the apollo client options by overriding the Apollo service (there is an example in the readme). Please let us know if that doesn't work! :v:
