### ISSUE TITLE
Cannot set property '_apolloObservable' of null

### ISSUE THREAD

**Issue by nalbina** [bgentry/ember-apollo-client#64]
I am having an issue with ember-apollo-client giving me this error when there are no documents found using the query.

With this particular Endpoint, When there is no matching Document, I get this response in graphiql and the `Cannot set property '_apolloObservable' of null` Error in the console.
```
{
  "data": {
    "Stat": null
  }
}
```

When there is a matching Document, I get this response in graphiql and no error in ember:
```
{
  "data": {
    "Stat": {
      "id": "cj8tubzz517jl0150uro8lvze",
      "level": 0
    }
  }
}
```
I would guess that it explodes because the ember-apollo-client wants to have an empty array on non documents but I am not sure.

Router
```
export default Ember.Route.extend(RouteQueryManager, {
    model(params) {
        const steamId = parseInt(params.steam_id)
        let variables = { steamId }
        return this.get('apollo').watchQuery({ query, variables }, "Stat");
    }
});
```
gql query
```
query StatsById($steamId: Int!) {
  Stat(steamId: $steamId) {
    id
    level
  }
}
```

Thanks :)

Addendum:
This renders to a simple template with {{model.level}}

Addendum2:
When I use `query` instead of `watchQuery` it works flawlessly.

**Comment by bgentry** [comment]
well, this seems like it would be a problem 😄 Not actually sure how we can solve this without changing the addon to return the full query result instead of just the payload.

If anybody has any other/better ideas, please chime in!

**Comment by nalbina** [comment]
Can you point me to the relevant code bit? I was trying to dig a bit around but I didn't really find where to change stuff :((

**Comment by bgentry** [comment]
Well, it's [this function](https://github.com/bgentry/ember-apollo-client/blob/aaa706d37c6e4b47945fd2d2765e10bdd07c90b6/addon/services/apollo.js#L29-L60) which gets called every time apollo has new data available for a watchQuery.

However, it's not a simple change to fix this. I think it's essentially a core design flaw with this addon that will require a breaking change in order to be fixed =/

**Comment by nalbina** [comment]
Okay, what is the payoff between query / watchQuery in the meantime. Would I need to do the polling manually?

**Comment by viniciussbs** [comment]
@nalbina I would return the full query result.

Instead of 

```javascript
return this.get('apollo').watchQuery({ query, variables }, "Stat");
```

I would return 

```javascript
return this.get('apollo').watchQuery({ query, variables });
```

And, into the template, `model.Stat`.

I don't recommend you to do this:

```javascript
return this.get('apollo').watchQuery({ query, variables }).then((data) => data.get("Stat"));
```

You can read [this old issue](https://github.com/bgentry/ember-apollo-client/issues/26) to know why.

**Comment by nalbina** [comment]
Thanks @viniciussbs. :)

**Comment by bgentry** [comment]
I suppose the answer for this is: if your query can return `null`, don't use the `resultKey`. If anybody thinks there's a good spot to add this to the readme, please PR it.

Meanwhile, I'll close this, because I'm not sure there's a way to fix it short of a large redesign that returns some sort of "query result" object rather than just the payload. This would be more similar to react-apollo, but it's not something I'm interested in undertaking given the breakage it would cause.
